# automatically generated by the FlatBuffers compiler, do not modify

# namespace: feather_v1_fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DateMetadata(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsDateMetadata(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DateMetadata()
        x.Init(buf, n + offset)
        return x

    # DateMetadata
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def DateMetadataStart(builder): builder.StartObject(0)
def DateMetadataEnd(builder): return builder.EndObject()
