# automatically generated by the FlatBuffers compiler, do not modify

# namespace: feather_v1_fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TimeMetadata(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsTimeMetadata(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TimeMetadata()
        x.Init(buf, n + offset)
        return x

    # TimeMetadata
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TimeMetadata
    def Unit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def TimeMetadataStart(builder): builder.StartObject(1)
def TimeMetadataAddUnit(builder, unit): builder.PrependInt8Slot(0, unit, 0)
def TimeMetadataEnd(builder): return builder.EndObject()
