# automatically generated by the FlatBuffers compiler, do not modify

# namespace: feather_v1_fbs

class TypeMetadata(object):
    NONE = 0
    CategoryMetadata = 1
    TimestampMetadata = 2
    DateMetadata = 3
    TimeMetadata = 4

