# automatically generated by the FlatBuffers compiler, do not modify

# namespace: feather_v1_fbs

# Feather is an experimental serialization format implemented using
# techniques from Apache Arrow. It was created as a proof-of-concept of an
# interoperable file format for storing data frames originating in Python or
# R. It enabled the developers to sidestep some of the open design questions
# in Arrow from early 2016 and instead create something simple and useful for
# the intended use cases.
class Type(object):
    BOOL = 0
    INT8 = 1
    INT16 = 2
    INT32 = 3
    INT64 = 4
    UINT8 = 5
    UINT16 = 6
    UINT32 = 7
    UINT64 = 8
    FLOAT = 9
    DOUBLE = 10
    UTF8 = 11
    BINARY = 12
    CATEGORY = 13
    TIMESTAMP = 14
    DATE = 15
    TIME = 16
    LARGE_UTF8 = 17
    LARGE_BINARY = 18

